### ISSUE TITLE
Activate Workflow

### ISSUE THREAD

**Issue by mike4git** [teamneusta/converter-bundle#13]
We need a workflow running for each PR to guarantee:

- [x]  Checkstyle fixed
- [x]  No Phpstan errors
- [x]  Tests all running green
- [x]  Test Coverage of new code is at least 80%
- [x]  Analyze layer rules with deptrac

**Comment by mike4git** [comment]
@jdreesen
What would you think about this way: https://itnext.io/github-actions-code-coverage-without-third-parties-f1299747064d
???

**Comment by lukadschaak** [comment]
I have that Link already in my bookmarks :) But the priority is very low. So when you have time, feel free.
