### ISSUE TITLE
ConverterStrategyHandler

### ISSUE THREAD

**Issue by mike4git** [teamneusta/converter-bundle#22]
In some situations you will need a converter which is choosing the correct converter by some circumstances (e.g. correct object type, country, you are converting for, language based or other environment settings).

So, there should be a `ConverterStrategyHandler`, which is of course a Converter itself but uses other converters to do the work.
Maybe the strategy which converter should be chosen could be something like this:
```php
interface DetermineConversionService 
{
    /**
     * @returns string which is the associated array key of the list of converters
     */
    public function determine(object $source, object $ctx): string
}
```

Implementation of `ConverterStrategyHandler` could be something like this:
```php
class ConverterStrategyHandler implements Converter
{
    public function __construct(
        private DetermineConversionService $determineConversionService,
        private array $converters = []
    ) {
    }

    public function convert(object $source, object $ctx): object
    {
        if ($criterium = $this->determineConversionService->determine($source, $ctx)) {
            return $this->converters[$criterium]->convert($source, $ctx);
        }

        return null;
    }
}
```

**Comment by jdreesen** [comment]
Yes, we should offer something like this.

The problem with the suggested `ConverterStrategyHandler` is that `Converter::convert()` doesn't allow returning `null`. So we would either have to change the `Converter` interface or throw in `ConverterStrategyHandler`.
