### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by lukadschaak** [teamneusta/converter-bundle#34]
What tasks are open to create a 1.0 release and put this bundle to packagist?

**Comment by jdreesen** [comment]
I'd like to do some cleanup regarding the class names/namespaces and exceptions fist.

**Comment by jdreesen** [comment]
While working on #35, I realized that the cache support is not yet ready for a `v1.0`. 
One problem is, that it doesn't take the context into account at all.

Maybe we should take it out before release, revise it, and add it back in a later feature release.

**Comment by jdreesen** [comment]
> I'd like to do some cleanup regarding the class names/namespaces and exceptions fist.

Did this in #37.

> Maybe we should take it out before release, revise it, and add it back in a later feature release.

Did this in #36 and #35.

**Comment by lukadschaak** [comment]
So, Release 1.0 was already created. Is this closed?
