### ISSUE TITLE
Docs shouldn't be excluded from release

### ISSUE THREAD

**Issue by nehlsen** [teamneusta/converter-bundle#51]
When I use a bundle and wonder how to use it, I often look into its documentation in exactly the version installed. I just tried to do the same with the converter bundle, just to discover that it is gone.

**Comment by jdreesen** [comment]
You really look into the docs inside the vendor folder?

**Comment by nehlsen** [comment]
Indeed i am :)

**Comment by lukadschaak** [comment]
I think docs should be exluded, because docs can contain binaries like images. And when releases are downloaded thousands of times, smaller is better.
