### ISSUE TITLE
PHP 8.4

### ISSUE THREAD

**Issue by nsd0nweigel** [teamneusta/converter-bundle#83]
Currently, PHP 8.4 is not supported, but it should.

**Comment by jdreesen** [comment]
Would you be up for creating a PR? 

It would probably be the same as #66 plus updating the `compose.yaml`.

**Comment by lukadschaak** [comment]
Ich mach das mal

**Comment by nehlsen** [comment]
Cool! Thanx @lukadschaak & @jdreesen !!!
Can we now get an installable Version? Something like `1.6.1`?

**Comment by jdreesen** [comment]
Sure. I want to wait a bit for #84. But I'll cut a release later today.

**Comment by jdreesen** [comment]
I just tagged the release: https://github.com/teamneusta/converter-bundle/releases/tag/v1.7.0
